#!/usr/bin/env python3
"""Render the control traceability matrix from controls/sctm.yaml.

The YAML is the source of truth. This produces the readable matrix from it, so
the two cannot disagree -- a hand-maintained copy always ends up describing a
system that has moved on.

Usage:
  python3 tools/render_sctm.py                      # write docs/CONTROL-MATRIX.md
  python3 tools/render_sctm.py --check              # fail if the file is stale
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from collections import Counter
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    raise SystemExit("PyYAML is required: pip install pyyaml")

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = PACKAGE_ROOT / "docs" / "CONTROL-MATRIX.md"

STATUS_LABEL = {
    "implemented": "Implemented",
    "partial": "Partial",
    "planned": "Planned",
    "inherited": "Inherited",
    "not-applicable": "N/A",
}

# Families in the order an assessor expects to read them.
FAMILY_NAMES = {
    "AC": "Access Control",
    "AU": "Audit and Accountability",
    "CA": "Assessment, Authorization and Monitoring",
    "CM": "Configuration Management",
    "CP": "Contingency Planning",
    "IA": "Identification and Authentication",
    "IR": "Incident Response",
    "PE": "Physical and Environmental Protection",
    "RA": "Risk Assessment",
    "SA": "System and Services Acquisition",
    "SC": "System and Communications Protection",
    "SI": "System and Information Integrity",
}


def flatten(text: str) -> str:
    """Collapse wrapped YAML prose into one table-safe line."""
    return " ".join(str(text).split()).replace("|", "\\|")


def render(sctm: dict) -> str:
    system = sctm.get("system", {})
    controls = sctm.get("controls", [])
    counts = Counter(c["status"] for c in controls)

    lines = [
        "# Control Traceability Matrix",
        "",
        "<!-- GENERATED by tools/render_sctm.py from controls/sctm.yaml — do not edit. -->",
        "",
        f"**System:** {system.get('name')} ({system.get('identifier')})  ",
        f"**Categorization:** confidentiality {system.get('categorization', {}).get('confidentiality')}, "
        f"integrity {system.get('categorization', {}).get('integrity')}, "
        f"availability {system.get('categorization', {}).get('availability')}  ",
        f"**Controls documented:** {len(controls)}",
        "",
        "| Status | Count |",
        "|---|---|",
    ]
    for status in ("implemented", "partial", "planned", "inherited", "not-applicable"):
        if counts.get(status):
            lines.append(f"| {STATUS_LABEL[status]} | {counts[status]} |")

    lines += [
        "",
        "Every *implemented* control below cites evidence that exists in the "
        "Evergreen repository, and where an automated check covers it, that check "
        "is passing. `tools/validate_package.py` enforces both.",
        "",
    ]

    by_family: dict = {}
    for control in controls:
        by_family.setdefault(control["id"].split("-")[0], []).append(control)

    for family in sorted(by_family):
        lines += [
            f"## {family} — {FAMILY_NAMES.get(family, family)}",
            "",
            "| Control | Title | Status | Owner | Automated checks | POA&M |",
            "|---|---|---|---|---|---|",
        ]
        for control in sorted(by_family[family], key=lambda c: c["id"]):
            checks = ", ".join(control.get("automated_checks") or []) or "—"
            poam = ", ".join(control.get("poam") or []) or "—"
            lines.append(
                f"| `{control['id']}` | {flatten(control['title'])} "
                f"| {STATUS_LABEL.get(control['status'], control['status'])} "
                f"| {control.get('responsibility', '—')} | {checks} | {poam} |"
            )
        lines.append("")

        for control in sorted(by_family[family], key=lambda c: c["id"]):
            lines += [
                f"### {control['id']} — {flatten(control['title'])}",
                "",
                f"**Status:** {STATUS_LABEL.get(control['status'], control['status'])} · "
                f"**Responsibility:** {control.get('responsibility', '—')}",
                "",
                flatten(control["implementation"]),
                "",
            ]
            if control.get("limitation"):
                lines += [f"> **Limitation.** {flatten(control['limitation'])}", ""]
            evidence = control.get("evidence") or []
            if evidence:
                lines.append("**Evidence**")
                lines.append("")
                for entry in evidence:
                    where = entry.get("repo", "evergreen")
                    prefix = "handoff:" if where == "handoff" else "evergreen:"
                    note = flatten(entry.get("note", ""))
                    lines.append(f"- `{prefix}{entry['path']}` — {note}" if note
                                 else f"- `{prefix}{entry['path']}`")
                lines.append("")

    lines += [
        "---",
        "",
        f"Generated {dt.date.today().isoformat()} from `controls/sctm.yaml`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the rendered file is out of date")
    args = parser.parse_args()

    sctm = yaml.safe_load((PACKAGE_ROOT / "controls" / "sctm.yaml").read_text(encoding="utf-8"))
    rendered = render(sctm)

    if args.check:
        if not OUTPUT.exists():
            print(f"{OUTPUT.relative_to(PACKAGE_ROOT)} has not been generated.")
            return 1
        # The trailing generation date changes daily; compare everything above it.
        current = OUTPUT.read_text(encoding="utf-8").split("---\n\nGenerated ")[0]
        if current != rendered.split("---\n\nGenerated ")[0]:
            print(f"{OUTPUT.relative_to(PACKAGE_ROOT)} is stale — run tools/render_sctm.py")
            return 1
        print(f"{OUTPUT.relative_to(PACKAGE_ROOT)} is up to date.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(PACKAGE_ROOT)} ({len(sctm.get('controls', []))} controls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
